apiVersion: v1
kind: ResourceQuota
metadata:
  name: clusterscope-postgres-quota
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    pods: "3"
    requests.cpu: "300m"
    requests.memory: "384Mi"
    limits.cpu: "1,5"
    limits.memory: "1536Mi"
