apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterscope-backend
  namespace: clusterscope
  labels:
    app: clusterscope-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: clusterscope-backend

  template:
    metadata:
      labels:
        app: clusterscope-backend

    spec:
      containers:
        - name: backend
          image: ghcr.io/hasan92mari/clusterscope-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000
              protocol: TCP

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: APP_NAME
              value: clusterscope-backend

            # PostgreSQL connection
            - name: DATABASE_URL
              value: "postgresql+psycopg://clusterscope:$(POSTGRES_PASSWORD)@clusterscope-postgres.clusterscope.svc.cluster.local:5432/clusterscope"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clusterscope-postgres
                  key: password

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault