apiVersion: v1
kind: PersistentVolume
metadata:
  name: clusterscope-redis-pv
spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /tmp/clusterscope-redis-data
    type: DirectoryOrCreate
