apiVersion: v1
kind: Secret
metadata:
  name: clusterscope-redis
  namespace: clusterscope
type: Opaque
stringData:
  password: "clusterscope-dev-password"
  url: "redis://:clusterscope-dev-password@clusterscope-redis:6379"