apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: clusterscope-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clusterscope-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: clusterscope-secrets
    kind: SecretStore
  target:
    name: clusterscope-postgres
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: cluster1-eks/clusterscope/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: cluster1-eks/clusterscope/postgres
        property: password
        property: port