apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clusterscope-backend-netpol
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  podSelector:
    matchLabels:
      app: clusterscope-backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: clusterscope-frontend
          podSelector:
            matchLabels:
              app: clusterscope-frontend
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: clusterscope-postgres
          podSelector:
            matchLabels:
              app: clusterscope-postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
      - ipBlock:
          cidr: 192.168.64.13/32  # 'kubernetes' service cluster IP endpoint
      ports:
        - protocol: TCP
          port: 6443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
