apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterscope-backend
subjects:
  - kind: ServiceAccount
    name: clusterscope-backend
    namespace: clusterscope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clusterscope-backend
