apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: clusterscope-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider: azure
  secretObjects:
    - secretName: clusterscope-postgres
      type: Opaque
      data:
        - objectName: postgres-username
          key: username
        - objectName: postgres-password
          key: password
        - objectName: postgres-database
          key: database
        - objectName: postgres-host
          key: host
        - objectName: postgres-port
          key: port
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 60a79d3a-c4d9-4f6e-a755-73519af6a3e2 #REPLACE_WITH_NORTHCENTRALUS_CSI_IDENTITY_CLIENT_ID 
    keyvaultName: clusterscope-0re8lc2i #REPLACE_WITH_NORTHCENTRALUS_KEY_VAULT_NAME
    tenantId: 2a8d0d4c-d928-419a-91a9-9e8846a69ff9
    objects: |
      array:
        - |
          objectName: postgres-username
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: postgres-database
          objectType: secret
        - |
          objectName: postgres-host
          objectType: secret
        - |
          objectName: postgres-port
          objectType: secret