apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterscope-config
  namespace: clusterscope
data:
  backend-url: "http://clusterscope-backend.clusterscope.svc.cluster.local:8000"
  redis-host: "clusterscope-redis.clusterscope.svc.cluster.local"
  redis-port: "6379"