apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterscope-frontend
  namespace: clusterscope

spec:
  replicas: 1

  selector:
    matchLabels:
      app: clusterscope-frontend

  template:
    metadata:
      labels:
        app: clusterscope-frontend

    spec:
      serviceAccountName: clusterscope-frontend

      containers:
        - name: frontend
          image: ghcr.io/hasan92mari/clusterscope-frontend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            # readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']

            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: clusterscope-frontend-config
                  key: backend-url

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: clusterscope-frontend-config
                  key: redis-host

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: clusterscope-frontend-config
                  key: redis-port

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clusterscope-redis
                  key: password