apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterscope-frontend
  namespace: clusterscope
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clusterscope-frontend
  template:
    metadata:
      labels:
        app: clusterscope-frontend
    spec:
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      containers:
        - name: frontend
          image: ghcr.io/hasan92mari/clusterscope-frontend:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
          - name: nginx-cache
            mountPath: /var/cache/nginx
          - name: nginx-run
            mountPath: /var/run/nginx