apiVersion: v1
kind: Service
metadata:
  name: clusterscope-frontend
  namespace: clusterscope
spec:
  selector:
    app: clusterscope-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP