{{- if .Values.backend.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clusterscope-backend
  namespace: {{ include "clusterscope.backendNamespace" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
{{- end }}
