{{- if and .Values.backend.enabled (ne .Values.namespaceMode "single") }}

apiVersion: v1
kind: Secret
metadata:
  name: clusterscope-postgres
  namespace: {{ include "clusterscope.backendNamespace" . }}
type: Opaque
stringData:
  username: {{ .Values.backend.postgres.username | quote }}
  password: {{ .Values.backend.postgres.password | quote }}
  database: {{ .Values.backend.postgres.database | quote }}

{{- end }}