apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clusterscope-frontend
  namespace: {{ include "clusterscope.frontendNamespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get