apiVersion: v1
kind: Secret
metadata:
  name: clusterscope-redis
  namespace: {{ include "clusterscope.frontendNamespace" . }}
type: Opaque
stringData:
  password: {{ .Values.frontend.redisPassword | quote }}