{{- if .Values.gateway.enabled }}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: clusterscope-gateway
  namespace: {{ include "clusterscope.gatewayNamespace" . }}

spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}

  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: {{ .Values.gateway.hostname }}

      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gateway.tls.existingSecret }}

      allowedRoutes:
        namespaces:
          {{- if eq .Values.namespaceMode "single" }}
          from: Same
          {{- else }}
          from: All
          {{- end }}

{{- end }}