{{- if and .Values.redis.enabled (ne .Values.namespaceMode "single") }}

apiVersion: v1
kind: Secret
metadata:
  name: clusterscope-redis
  namespace: {{ include "clusterscope.redisNamespace" . }}
type: Opaque
stringData:
  password: {{ .Values.redis.password | quote }}

{{- end }}
