apiVersion: alb.networking.azure.io/v1
kind: ApplicationLoadBalancer
metadata:
  name: clusterscope-alb
  namespace: clusterscope-frontend
spec:
  associations:
    - /subscriptions/4a63a39d-cb27-48c4-88f2-0c33a4b9dfdb/resourceGroups/MC_aks_cluster1-aks_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-17547948/subnets/aks-appgateway
