apiVersion: v1
kind: ResourceQuota
metadata:
  name: clusterscope-redis-quota
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hard:
    pods: "3"
    requests.cpu: "150m"
    requests.memory: "192Mi"
    limits.cpu: "600m"
    limits.memory: "768Mi"
