{{- if .Values.postgres.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: clusterscope-postgres
  namespace: {{ include "clusterscope.postgresNamespace" . }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}

{{- end }}
