{{- if .Values.redis.enabled }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: clusterscope-redis-pv
spec:
  capacity:
    storage: {{ .Values.redis.storage.size }}

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: {{ .Values.redis.storage.hostPath }}
    type: DirectoryOrCreate

{{- end }}
