apiVersion: v1
kind: PersistentVolume
metadata:
  name: clusterscope-postgres-pv

spec:
  capacity:
    storage: 1Gi
    storageClassName: local-path

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain
