apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: clusterscope-project
  namespace: argocd
spec:
  description: Project for ClusterScope application workloads and external-secret synchronization
  sourceNamespaces:
    - argocd
  sourceRepos:
    - https://github.com/hasan92mari/clusterscope.git
  destinations:
    - namespace: clusterscope-*
      name: cluster1-eks
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: LimitRange
    - group: ""
      kind: ResourceQuota
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "gateway.networking.k8s.io"
      kind: Gateway
    - group: "gateway.networking.k8s.io"
      kind: HTTPRoute
    - group: external-secrets.io
      kind: SecretStore
    - group: external-secrets.io
      kind: ExternalSecret
    - group: "gateway.k8s.aws"
      kind: LoadBalancerConfiguration
    - group: "gateway.k8s.aws"
      kind: TargetGroupConfiguration
  clusterResourceBlacklist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  roles:
    - name: dev-readonly
      description: Read-only access for developers
      policies:
        - p, proj:app1-project:dev-readonly, applications, get, app1-project/*, allow
      groups:
        - app1-devs
    - name: platform-admin
      description: Full control for platform team
      policies:
        - p, proj:app1-project:platform-admin, applications, *, app1-project/*, allow
      groups:
        - platform-team
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusterscope
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/hasan92mari/clusterscope.git
              revision: HEAD
              directories:
                - path: argo/*
                - path: argo/postgres
                  exclude: true
                - path: argo/redis
                  exclude: true
                - path: argo/argocd-crds
                  exclude: true
          - list:
              elements:
                # - Name: prod
                #   branch: main
                - Name: dev
                  branch: aws-eks
  template:
    metadata:
      name: 'clusterscope-{{.Name}}-{{.path.basename}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: clusterscope-project
      source:
        repoURL: https://github.com/hasan92mari/clusterscope.git
        targetRevision: '{{.branch}}'
        path: '{{.path.path}}'
      destination:
        name: cluster1-eks
        namespace: 'clusterscope-{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PruneLast=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
