name: Release Charts

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/helm-ci.yaml'

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    #   - name: Ensure gh-pages branch exists
    #     run: |
    #       git fetch origin
    #       if git ls-remote --exit-code --heads origin gh-pages >/dev/null 2>&1; then
    #         echo "gh-pages branch already exists"
    #       else
    #         git checkout --orphan gh-pages
    #         git rm -rf . || true
    #         git commit --allow-empty -m "Initialize gh-pages"
    #         git push origin gh-pages
    #         git checkout "${GITHUB_REF_NAME:-main}"
    #       fi

      - name: Package and publish Helm chart
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm
          pages_branch: gh-pages
          mark_as_latest: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
