name: Release Charts

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/helm-ci.yaml'

jobs:
  release:
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Package and publish Helm chart
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: helm
          pages_branch: gh-pages
          mark_as_latest: true
        env:
          CR_TOKEN: "${{ secrets.GHCR_TOKEN }}"
